import Head from 'next/head'
import Accordion from '../components/Accordion'
import Header from '../components/Header'




export default function Home() {
  return (
    <>
      <Head>
        <title>M:R</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='px-4 py-3'>
          <Header />
        </section>
       <Accordion/>
      </main>
    </>
  )
}
